/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.universita.ilparolierelabb.server;

import com.universita.ilparolierelabb.common.Utility;

/**
 *
 * @author andreagirola
 */
public class GameMatrix extends javax.swing.JFrame {

    /**
     * Creates new form GameMatrix
     */
    public GameMatrix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        box1 = new javax.swing.JLabel();
        box2 = new javax.swing.JLabel();
        box4 = new javax.swing.JLabel();
        box3 = new javax.swing.JLabel();
        box5 = new javax.swing.JLabel();
        box6 = new javax.swing.JLabel();
        box7 = new javax.swing.JLabel();
        box8 = new javax.swing.JLabel();
        box9 = new javax.swing.JLabel();
        box12 = new javax.swing.JLabel();
        box10 = new javax.swing.JLabel();
        box11 = new javax.swing.JLabel();
        box13 = new javax.swing.JLabel();
        box16 = new javax.swing.JLabel();
        box14 = new javax.swing.JLabel();
        box15 = new javax.swing.JLabel();
        fillMatrix = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        box1.setText("jLabel1");
        jPanel1.add(box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 11, -1, 39));

        box2.setText("jLabel2");
        jPanel1.add(box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 11, -1, 39));

        box4.setText("jLabel4");
        jPanel1.add(box4, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 11, -1, 39));

        box3.setText("jLabel3");
        jPanel1.add(box3, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 11, -1, 39));

        box5.setText("jLabel1");
        jPanel1.add(box5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 68, -1, 39));

        box6.setText("jLabel2");
        jPanel1.add(box6, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 68, -1, 39));

        box7.setText("jLabel3");
        jPanel1.add(box7, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 68, -1, 39));

        box8.setText("jLabel4");
        jPanel1.add(box8, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 68, -1, 39));

        box9.setText("jLabel1");
        jPanel1.add(box9, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 125, -1, 39));

        box12.setText("jLabel4");
        jPanel1.add(box12, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 125, -1, 39));

        box10.setText("jLabel2");
        jPanel1.add(box10, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 125, -1, 39));

        box11.setText("jLabel3");
        jPanel1.add(box11, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 125, -1, 39));

        box13.setText("jLabel1");
        jPanel1.add(box13, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 175, -1, 39));

        box16.setText("jLabel4");
        jPanel1.add(box16, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 175, -1, 39));

        box14.setText("jLabel2");
        jPanel1.add(box14, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 175, -1, 39));

        box15.setText("jLabel3");
        jPanel1.add(box15, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 175, -1, 39));

        fillMatrix.setText("jToggleButton1");
        fillMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillMatrixActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fillMatrix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(fillMatrix)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(327, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillMatrixActionPerformed

        
        
    }//GEN-LAST:event_fillMatrixActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Dice[] d = DiceFactory.CreateDices();
        
        // TODO : Matrix.CreateDices();
        // String[][] matgrice =  Matrix.getMatrix();
        box1.setText(d[0].getRandomFace());
        box2.setText(d[1].getRandomFace());
        box3.setText(d[2].getRandomFace());
        box4.setText(d[3].getRandomFace());
        box5.setText(d[4].getRandomFace());
        box6.setText(d[5].getRandomFace());
        box7.setText(d[6].getRandomFace());
        box8.setText(d[7].getRandomFace());
        box9.setText(d[8].getRandomFace());
        box10.setText(d[9].getRandomFace());
        box11.setText(d[10].getRandomFace());
        box12.setText(d[11].getRandomFace());
        box13.setText(d[12].getRandomFace());
        box14.setText(d[13].getRandomFace());
        box15.setText(d[14].getRandomFace());
        box16.setText(d[15].getRandomFace());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameMatrix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel box1;
    private javax.swing.JLabel box10;
    private javax.swing.JLabel box11;
    private javax.swing.JLabel box12;
    private javax.swing.JLabel box13;
    private javax.swing.JLabel box14;
    private javax.swing.JLabel box15;
    private javax.swing.JLabel box16;
    private javax.swing.JLabel box2;
    private javax.swing.JLabel box3;
    private javax.swing.JLabel box4;
    private javax.swing.JLabel box5;
    private javax.swing.JLabel box6;
    private javax.swing.JLabel box7;
    private javax.swing.JLabel box8;
    private javax.swing.JLabel box9;
    private javax.swing.JToggleButton fillMatrix;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
