/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.universita.ilparolierelabb.client.frames;

import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Momo
 */
public class LobbyUsrControl extends javax.swing.JPanel {

    private DefaultTableModel _tablemodel = new DefaultTableModel(new String[] {"Room ID","Date","Users"},0);
    public LobbyUsrControl() 
    {
        initComponents();
        jTableRooms.setModel(_tablemodel);
        jTableRooms.setDefaultEditor(Object.class, null);
        jTableRooms.setColumnSelectionAllowed(false);
        jTableRooms.setRowSelectionAllowed(true);
        jTableRooms.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    public void addRoom(String id,String date,String players)
    {
        _tablemodel.addRow(new String[]{id,date,players});
    }
    public void removeRoom(String id)
    {
        //_tablemodel.removeRow();
    }
    public void removeAllRooms()
    {
        _tablemodel.setRowCount(0);
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTableContainer = new javax.swing.JScrollPane();
        jTableRooms = new javax.swing.JTable();
        panelListContainer = new javax.swing.JScrollPane();
        jListPlayers = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        btnAddRoom = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new java.awt.BorderLayout());

        jTableRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Date", "Users"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRooms.setColumnSelectionAllowed(true);
        jTableRooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRoomsMouseClicked(evt);
            }
        });
        panelTableContainer.setViewportView(jTableRooms);
        jTableRooms.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        add(panelTableContainer, java.awt.BorderLayout.CENTER);

        jListPlayers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        panelListContainer.setViewportView(jListPlayers);

        add(panelListContainer, java.awt.BorderLayout.LINE_END);

        btnAddRoom.setText("Add room");
        jPanel1.add(btnAddRoom);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableRoomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRoomsMouseClicked
        // TODO add your handling code here:
        int selected = jTableRooms.getSelectedRow();
        if(selected == -1) return;
    }//GEN-LAST:event_jTableRoomsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JList<String> jListPlayers;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTableRooms;
    private javax.swing.JScrollPane panelListContainer;
    private javax.swing.JScrollPane panelTableContainer;
    // End of variables declaration//GEN-END:variables
}
